[project]
name = "ballista"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hydra-core>=1.3.2",
    "omegaconf>=2.3.0",
    "opencv-python>=4.12.0.88",
    "rich>=14.2.0",
    "torch>=2.9.1",
]
