task_name: traj

dataset:
  reality_root: ${oc.env:BALLISTA_REALITY_ROOT,null}      # Optional[str]
  synthesis_root: ${oc.env:BALLISTA_SYNTHESIS_ROOT,null}  # Optional[str]
  mode: both  # reality | synthesis | both

  # TrackNet 默认输入尺寸：(H,W)=(288,512)，这里用 (W,H) 表示
  out_size: [512, 288]

  # 3 帧输入 -> 3 个 heatmap 输出
  seq_len: 3
  sliding_step: 1
  sigma: 2.5
  batch_size: 4
  num_workers: 0

model:
  name: tracknet
  # in_dim = seq_len * 3 (RGB)
  in_dim: 9
  out_dim: ${dataset.seq_len}

loss:
  name: wbce_loss
  reduction: mean
  eps: 1e-7
  
optimizer:
  type: adamw
  lr: 0.001
  weight_decay: 0.0001
